# action.yaml
name: 'Coupon Track Github Action'

on:
  schedule:
    # Runs every 15 minutes
    - cron: "15 * * * *"
  workflow_dispatch:

jobs:
  CouponBot:
    name: "run"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout branch "master"
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      - name: Install Dependencies
        run: pip install -r requirements.txt
        shell: bash
      - name: Run python bot.py
        run: python coupon_track_bot.py
        shell: bash
